### ISSUE TITLE
exporting TF2 models

### ISSUE THREAD

**Issue by esgomezm** [deepimagej/pydeepimagej#1]
https://github.com/deepimagej/pydeepimagej/blob/77593fb6c2f5fe268c9310a55b2fc530effec561/pydeepimagej/xml/create_config.py#L331

@cmohl2013, please find in those lines some code

**Comment by cmohl2013** [comment]
@esgomezm

Thank you, very helpul! I was not aware of pydeepimagej until Friday. Would have been better to use pydeepimagej rather than implementing the same in yapic. Maybe we can include pydeepimagej in our exporter in the future.

**Comment by esgomezm** [comment]
It's rather new so you didn't really miss anything :) Once the new release of DeepImageJ is out and stable, it should be quite easy to integrate this library to YAPIC and forget about updating the format.
